apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: distributed-app
spec:
  components:
    - name: edge-module-1
      type: edge-worker
      properties:
        image: synadia/nats-box:latest
        name: nats-box1
        command:
          - /bin/sh
          - -c
          - --
        args:
          - "while true; do sleep 1; done;"
    - name: edge-module-2
      type: edge-worker
      properties:
        image: synadia/nats-box:latest
        name: nats-box1
        command:
          - /bin/sh
          - -c
          - --
        args:
          - "while true; do sleep 1; done;"
        # network-rbac:
        #   - heike-flo
    - name: distributed-app-network
      type:
        application-network
        # usernames:
        #   - asdf
        #   - asdf2
    # - name: distrubuted-app-network-rbac
    #   type: network-rbac
    #     heike-flo:
    #       write:
    #         - heike
    #         - test
    #       read:
    #         - flo
    #         - asdf
    #     kaesbrot-klausi:
    #       read:
    #         - klausi
