apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: distributed-app
spec:
  components:
    - name: main-module
      type: main-worker
      properties:
        image: nginx
        name: nginx-main
    - name: edge-module-2
      type: edge-worker
      properties:
        image: nginx
        name: nginx-edge-2
    - name: distributed-app-network
      type: application-network
